"""
RescueNet AI — Python seed data for mock_db.py
These dicts mirror the SQL seed data and are loaded into the in-memory store.
"""

SEED_INCIDENTS = [
    {
        "id": "demo-001",
        "title": "Major Flooding in South Mumbai",
        "type": "flood",
        "description": "Severe flooding after 3-day monsoon. Multiple residential areas submerged. Roads blocked.",
        "location": "South Mumbai, Maharashtra, India",
        "latitude": 18.9220,
        "longitude": 72.8347,
        "severity": 4,
        "status": "active",
        "created_at": "2024-06-15T06:00:00Z",
    },
    {
        "id": "demo-002",
        "title": "Earthquake — Jaipur Industrial Zone",
        "type": "earthquake",
        "description": "Magnitude 6.2 earthquake. Industrial buildings collapsed. Multiple workers trapped.",
        "location": "Jaipur, Rajasthan, India",
        "latitude": 26.9124,
        "longitude": 75.7873,
        "severity": 5,
        "status": "active",
        "created_at": "2024-06-15T07:30:00Z",
    },
    {
        "id": "demo-003",
        "title": "Chemical Plant Fire — Pune",
        "type": "fire",
        "description": "Fire at chemical storage facility. Hazardous gas leak reported.",
        "location": "Pune, Maharashtra, India",
        "latitude": 18.5204,
        "longitude": 73.8567,
        "severity": 3,
        "status": "reported",
        "created_at": "2024-06-15T09:00:00Z",
    },
    {
        "id": "demo-004",
        "title": "Cyclone Landfall — Odisha Coast",
        "type": "cyclone",
        "description": "Category 3 cyclone making landfall. Coastal villages at risk.",
        "location": "Puri, Odisha, India",
        "latitude": 19.8135,
        "longitude": 85.8312,
        "severity": 5,
        "status": "active",
        "created_at": "2024-06-15T10:15:00Z",
    },
    {
        "id": "demo-005",
        "title": "Landslide — Himachal Highway",
        "type": "landslide",
        "description": "Major landslide blocking National Highway 5. Multiple vehicles buried.",
        "location": "Shimla, Himachal Pradesh, India",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "severity": 3,
        "status": "reported",
        "created_at": "2024-06-15T11:00:00Z",
    },
]

SEED_HOSPITALS = [
    {
        "id": "hosp-001",
        "name": "KEM Hospital",
        "address": "Acharya Donde Marg, Parel",
        "city": "Mumbai",
        "latitude": 19.0027,
        "longitude": 72.8397,
        "total_beds": 800,
        "available_beds": 120,
        "icu_beds": 30,
        "specializations": ["trauma", "burns", "pediatric", "neurology"],
        "contact_phone": "+91-22-24107000",
        "is_active": True,
    },
    {
        "id": "hosp-002",
        "name": "Nair Hospital",
        "address": "Dr. A. L. Nair Road, Mumbai Central",
        "city": "Mumbai",
        "latitude": 18.9697,
        "longitude": 72.8196,
        "total_beds": 650,
        "available_beds": 85,
        "icu_beds": 20,
        "specializations": ["trauma", "orthopedic", "cardiology"],
        "contact_phone": "+91-22-23027600",
        "is_active": True,
    },
    {
        "id": "hosp-003",
        "name": "Sawai Man Singh Hospital",
        "address": "Jawaharlal Nehru Marg",
        "city": "Jaipur",
        "latitude": 26.9036,
        "longitude": 75.7999,
        "total_beds": 1000,
        "available_beds": 200,
        "icu_beds": 45,
        "specializations": ["trauma", "burns", "orthopedic", "neurosurgery"],
        "contact_phone": "+91-141-2518888",
        "is_active": True,
    },
    {
        "id": "hosp-004",
        "name": "Sassoon General Hospital",
        "address": "Near Pune Railway Station",
        "city": "Pune",
        "latitude": 18.5277,
        "longitude": 73.8730,
        "total_beds": 700,
        "available_beds": 95,
        "icu_beds": 25,
        "specializations": ["trauma", "burns", "toxicology"],
        "contact_phone": "+91-20-26128000",
        "is_active": True,
    },
    {
        "id": "hosp-005",
        "name": "SCB Medical College Hospital",
        "address": "Mangalabag",
        "city": "Cuttack",
        "latitude": 20.4625,
        "longitude": 85.8828,
        "total_beds": 1200,
        "available_beds": 180,
        "icu_beds": 50,
        "specializations": ["trauma", "orthopedic", "cardiology", "disaster_response"],
        "contact_phone": "+91-671-2414388",
        "is_active": True,
    },
    {
        "id": "hosp-006",
        "name": "IGMC Shimla",
        "address": "Ridge Road, Shimla",
        "city": "Shimla",
        "latitude": 31.1008,
        "longitude": 77.1734,
        "total_beds": 350,
        "available_beds": 60,
        "icu_beds": 15,
        "specializations": ["trauma", "orthopedic"],
        "contact_phone": "+91-177-2658830",
        "is_active": True,
    },
]

SEED_RESOURCES = [
    {
        "id": "reso-001",
        "name": "Mumbai Ambulance Fleet A",
        "type": "ambulance",
        "quantity": 12,
        "available": 8,
        "location": "Central Dispatch, Mumbai",
        "latitude": 19.0760,
        "longitude": 72.8777,
        "status": "available",
    },
    {
        "id": "reso-002",
        "name": "Air Rescue Helicopter 1",
        "type": "helicopter",
        "quantity": 2,
        "available": 1,
        "location": "Juhu Airport, Mumbai",
        "latitude": 19.0990,
        "longitude": 72.8490,
        "status": "available",
    },
    {
        "id": "reso-003",
        "name": "NDRF Team Alpha",
        "type": "rescue_team",
        "quantity": 30,
        "available": 30,
        "location": "NDRF Base, Mumbai",
        "latitude": 19.0600,
        "longitude": 72.8350,
        "status": "available",
    },
    {
        "id": "reso-004",
        "name": "Fire Brigade Unit 7",
        "type": "fire_truck",
        "quantity": 6,
        "available": 4,
        "location": "Dadar Fire Station, Mumbai",
        "latitude": 19.0178,
        "longitude": 72.8478,
        "status": "available",
    },
    {
        "id": "reso-005",
        "name": "Jaipur Ambulance Fleet",
        "type": "ambulance",
        "quantity": 8,
        "available": 5,
        "location": "SMS Hospital Dispatch, Jaipur",
        "latitude": 26.9036,
        "longitude": 75.7999,
        "status": "available",
    },
    {
        "id": "reso-006",
        "name": "Rajasthan SDRF Team",
        "type": "rescue_team",
        "quantity": 25,
        "available": 20,
        "location": "SDRF Camp, Jaipur",
        "latitude": 26.8500,
        "longitude": 75.7800,
        "status": "available",
    },
    {
        "id": "reso-007",
        "name": "Odisha Coast Guard Boats",
        "type": "water_rescue",
        "quantity": 10,
        "available": 7,
        "location": "Puri Coast Guard Station",
        "latitude": 19.8000,
        "longitude": 85.8200,
        "status": "available",
    },
    {
        "id": "reso-008",
        "name": "Odisha Disaster Response Force",
        "type": "rescue_team",
        "quantity": 50,
        "available": 45,
        "location": "ODRAF HQ, Bhubaneswar",
        "latitude": 20.2961,
        "longitude": 85.8245,
        "status": "available",
    },
    {
        "id": "reso-009",
        "name": "HP Mountain Rescue Team",
        "type": "rescue_team",
        "quantity": 15,
        "available": 12,
        "location": "Shimla Mountain Rescue Base",
        "latitude": 31.1048,
        "longitude": 77.1734,
        "status": "available",
    },
    {
        "id": "reso-010",
        "name": "Pune Medical Response Unit",
        "type": "medical_unit",
        "quantity": 5,
        "available": 3,
        "location": "Sassoon Hospital, Pune",
        "latitude": 18.5277,
        "longitude": 73.8730,
        "status": "available",
    },
]
